import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="pb-16">{children}</div> {/* padding bottom for footer */}
        <footer className="fixed bottom-0 left-0 w-full flex justify-around bg-white p-2 border-t shadow-md">
          <a href="/vote" className="text-blue-600 font-semibold">
            Vote
          </a>
          <a href="/create" className="text-blue-600 font-semibold">
            Create
          </a>
          <a href="/profile" className="text-blue-600 font-semibold">
            Profile
          </a>
        </footer>
      </body>
    </html>
  );
}
